import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
         <header className="bg-white/80 backdrop-blur-sm border-b border-gray-200 ">
        <div className="max-w-7xl mx-24 px-2  lg:px-4">
          <div className="flex justify-between items-center py-4">
            <Link href="/" className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-lg">✉️</span>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">Email Agent</h1>
                <p className="text-sm text-gray-500">AI-Powered Email Processing</p>
              </div>
            </Link>
            <nav className="flex space-x-8">
              {/* <Link href="/" className="text-gray-700 hover:text-blue-600 font-medium transition-colors">
                samples
              </Link> */}
             
            </nav>
          </div>
        </div>
      </header>

        {children}
      </body>
    </html>
  );
}
